import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "../../../globals.css";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";
import Sidebar from "./_components/sidebar";
import Header from "./_components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {session} = await getUser()

  if (!session) {
    return redirect('/dashboard/sign-in')
  }
  
  return (
    <html lang="en">
      <body className={geistSans.variable}>
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
          <Sidebar />
          <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
            <Header />
            <main className="p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}